### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by AlJohri** [RupGautam/OSX-Setup#1]
Hey there, thanks for the star on my [dotfiles](https://github.com/AlJohri/dotfiles) repo!

I just made some major changes and would love any feedback. Pretty much just moved almost everything into a two files:
- https://github.com/AlJohri/dotfiles/blob/gh-pages/Brewfile
- https://github.com/AlJohri/dotfiles/blob/gh-pages/mac

Your repo also looks pretty cool. You might want to consider:
- using a commonrc between bash_profile and zshrc since you seem to use both
- using zshenv vs zshrc and if that affects you in any way (I end up using [zshenv](https://github.com/AlJohri/dotfiles/blob/gh-pages/templates/commonenv) because some of the linters I use with sublime required it)
- using the new [Brewfile](https://github.com/AlJohri/dotfiles/blob/gh-pages/Brewfile) (brew bundle command) that was released a few months back instead of manually writing brew install and brew cask install --appdir...

Thanks for your time!

**Comment by RupGautam** [comment]
@AlJohri  Thank you for peeking into my repo. 
I have moved over here [dev-setup](https://github.com/rupgautam/dev-setup), forked from [dev-setup](https://github.com/donnemartin/dev-setup). 

Thanks for zshenv suggestion, I will switch.

**Comment by AlJohri** [comment]
Thanks for the link, I'll check it out!
